name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [normal, mmap]

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Установка зависимостей
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Сборка проекта
        run: |
          mkdir -p build
          cd build
          if [ "${{ matrix.build_type }}" == "mmap" ]; then
            cmake -DUSE_MMAP=ON ..
          else
            cmake ..
          fi
          make

      - name: Запуск тестов
        run: |
          cd build
          ctest --output-on-failure